// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQotgu6LQbKfusZHZUXWK5nfaPyJTZJaE',
    appId: '1:548149846170:android:67a3b4b854e87235f97f23',
    messagingSenderId: '548149846170',
    projectId: 'login-5d7cd',
    storageBucket: 'login-5d7cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQotgu6LQbKfusZHZUXWK5nfaPyJTZJaE',
    appId: '1:548149846170:ios:2d0bb24b5fb97682f97f23',
    messagingSenderId: '548149846170',
    projectId: 'login-5d7cd',
    storageBucket: 'login-5d7cd.firebasestorage.app',
    iosBundleId: 'com.hangarymod.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQotgu6LQbKfusZHZUXWK5nfaPyJTZJaE',
    appId: '1:548149846170:ios:ec9f08cf53379205f97f23',
    messagingSenderId: '548149846170',
    projectId: 'login-5d7cd',
    storageBucket: 'login-5d7cd.firebasestorage.app',
    iosBundleId: 'com.hangarymod.test',
  );
}
